### ISSUE TITLE
[Bug] Scroll wheel use in combobox only toggles between top 2 items [sf#533]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/wxcatapult#31] opened 2015-06-24 13:47 UTC
**Reported by manuelbi on 2014-05-10 20:00 UTC**
...instead of going through all items.

I can reproduce this on Linux with wx 2.8. I checked some wxComboBox sample code and there it seems to work OK.

Bug reported after the 0.10.1 release on MRC.

**Comment by MBilderbeek** [comment] 2019-03-20 23:06
I can't reproduce this with current openMSX 0.15.0 on Linux with wx 3.0. Therefore closing.

**Closed as completed by MBilderbeek** 2019-03-20 23:06 UTC
Labels: bug, wxCatapult
